module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {},
  },
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#6A5ACD",
          "primary-focus": "#5A4ABD",
          "primary-content": "#ffffff",
          "secondary": "#4A5568",
          "secondary-focus": "#2D3748",
          "secondary-content": "#ffffff",
          "accent": "#718096",
          "accent-focus": "#4A5568",
          "accent-content": "#ffffff",
          "neutral": "#2D3748",
          "neutral-focus": "#1A202C",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#F7FAFC",
          "base-300": "#E2E8F0",
          "base-content": "#1A202C",
          "info": "#3182CE",
          "success": "#38A169",
          "warning": "#D69E2E",
          "error": "#E53E3E",
        },
      },
      {
        dark: {
          "primary": "#8B7DD8",
          "primary-focus": "#7B6DC8",
          "primary-content": "#ffffff",
          "secondary": "#64748B",
          "secondary-focus": "#475569",
          "secondary-content": "#ffffff",
          "accent": "#94A3B8",
          "accent-focus": "#64748B",
          "accent-content": "#ffffff",
          "neutral": "#1E293B",
          "neutral-focus": "#0F172A",
          "neutral-content": "#E2E8F0",
          "base-100": "#0F172A",
          "base-200": "#1E293B",
          "base-300": "#334155",
          "base-content": "#E2E8F0",
          "info": "#60A5FA",
          "success": "#4ADE80",
          "warning": "#FBBF24",
          "error": "#F87171",
        },
      },
    ],
  },
  plugins: [require('daisyui')],
};
