name: Build iOS App

on:
  push:
    branches: [ ios-app-development ]
  pull_request:
    branches: [ ios-app-development ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Meteor
      run: |
        curl https://install.meteor.com/ | sh
        export PATH="$HOME/.meteor:$PATH"
        echo "$HOME/.meteor" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        npm install
        meteor npm install
        
    - name: Clean Meteor build cache
      run: |
        echo "Cleaning Meteor build cache..."
        rm -rf .meteor/local/cordova-build || echo "No cordova-build cache to clean"
        rm -rf .meteor/local/build || echo "No build cache to clean"
        
    - name: Add iOS platform
      run: |
        meteor add-platform ios || echo "iOS platform already exists or failed to add"
        
    - name: Verify iOS platform
      run: |
        echo "Checking iOS platform..."
        ls -la .meteor/
        cat .meteor/platforms || echo "No platforms file found"
        
    - name: Build iOS app
      run: |
        echo "Building iOS app..."
        meteor build ./build --server=https://timeharbor.com
        
    - name: Verify build output
      run: |
        echo "Checking build output..."
        ls -la build/
        ls -la build/ios/ || echo "No iOS build found"
        ls -la build/ios/project/ || echo "No iOS project found"
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Check iOS project structure
      run: |
        cd build/ios/project
        echo "Current directory: $(pwd)"
        echo "Contents of iOS project directory:"
        ls -la
        echo "Looking for Podfile:"
        ls -la Podfile* || echo "No Podfile found"
        echo "Looking for workspace/project files:"
        find . -name "*.xcworkspace" -o -name "*.xcodeproj"
        
    - name: Skip CocoaPods (no dependencies needed)
      run: |
        cd build/ios/project
        echo "Skipping CocoaPods installation since we removed Google OAuth plugin"
        echo "This should build without external dependencies"
        
    - name: List iOS project contents
      run: |
        cd build/ios/project
        echo "Contents of iOS project directory:"
        ls -la
        echo "Looking for workspace files:"
        find . -name "*.xcworkspace" -o -name "*.xcodeproj"
        
    - name: Clean Xcode build
      run: |
        cd build/ios/project
        echo "Cleaning Xcode build..."
        if [ -f "Time Harbor.xcworkspace" ]; then
          xcodebuild -workspace "Time Harbor.xcworkspace" -scheme "Time Harbor" clean
        elif [ -d "Time Harbor.xcodeproj" ]; then
          xcodebuild -project "Time Harbor.xcodeproj" -scheme "Time Harbor" clean
        fi
        
    - name: Build iOS project [without CocoaPods]
      run: |
        cd build/ios/project
        # Use project file directly (no CocoaPods workspace needed)
        if [ -d "Time Harbor.xcodeproj" ]; then
          echo "Found Time Harbor.xcodeproj, building with project file"
          xcodebuild -project "Time Harbor.xcodeproj" -scheme "Time Harbor" -configuration Release -destination generic/platform=iOS LANGUAGE=en US_region=en -archivePath timeharbor.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        else
          echo "No project file found, listing all files:"
          ls -la
          exit 1
        fi
        
    - name: Create ExportOptions.plist
      run: |
        mkdir -p build/ios/project
        cat > build/ios/project/ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
        </dict>
        </plist>
        EOF
        
    - name: Export IPA file (unsigned)
      run: |
        cd build/ios/project
        echo "Attempting to export IPA without signing..."
        # Try to export without signing
        xcodebuild -exportArchive -archivePath timeharbor.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist -allowProvisioningUpdates || echo "Export with signing failed, trying alternative method"
        
        # Alternative: Try to extract the app from the archive manually
        if [ ! -f "*.ipa" ]; then
          echo "Standard export failed, trying to create IPA manually..."
          cd timeharbor.xcarchive/Products/Applications/
          zip -r ../../../TimeHarbor.ipa Time\ Harbor.app
          cd ../../..
          echo "Created IPA manually"
        fi
        
    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-build
        path: |
          build/ios/project/timeharbor.ipa
          build/ios/project/timeharbor.xcarchive
          build/ios/
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          build/
        retention-days: 7
