name: Build iOS App

on:
  push:
    branches: [ ios-app-development ]
  pull_request:
    branches: [ ios-app-development ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Meteor
      run: |
        curl https://install.meteor.com/ | sh
        export PATH="$HOME/.meteor:$PATH"
        echo "$HOME/.meteor" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        npm install
        meteor npm install
        
    - name: Add iOS platform
      run: |
        meteor add-platform ios || echo "iOS platform already exists or failed to add"
        
    - name: Verify iOS platform
      run: |
        echo "Checking iOS platform..."
        ls -la .meteor/
        cat .meteor/platforms || echo "No platforms file found"
        
    - name: Build iOS app
      run: |
        echo "Building iOS app..."
        meteor build ./build --server=https://timeharbor.com
        
    - name: Verify build output
      run: |
        echo "Checking build output..."
        ls -la build/
        ls -la build/ios/ || echo "No iOS build found"
        ls -la build/ios/project/ || echo "No iOS project found"
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install CocoaPods dependencies
      run: |
        cd build/ios/project
        pod install --repo-update
        
    - name: List iOS project contents
      run: |
        cd build/ios/project
        echo "Contents of iOS project directory:"
        ls -la
        echo "Looking for workspace files:"
        find . -name "*.xcworkspace" -o -name "*.xcodeproj"
        
    - name: Build iOS project with Xcode
      run: |
        cd build/ios/project
        # Try to find the correct workspace/project file
        if [ -f "Time Harbor.xcworkspace" ]; then
          echo "Found Time Harbor.xcworkspace, building with workspace"
          xcodebuild -workspace "Time Harbor.xcworkspace" -scheme "Time Harbor" -configuration Release -destination generic/platform=iOS -archivePath timeharbor.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        elif [ -d "Time Harbor.xcodeproj" ]; then
          echo "Found Time Harbor.xcodeproj, building with project"
          xcodebuild -project "Time Harbor.xcodeproj" -scheme "Time Harbor" -configuration Release -destination generic/platform=iOS -archivePath timeharbor.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        else
          echo "No workspace or project found, listing all files:"
          ls -la
          exit 1
        fi
        
    - name: Create ExportOptions.plist
      run: |
        mkdir -p build/ios/project
        cat > build/ios/project/ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>signingCertificate</key>
            <string></string>
            <key>teamID</key>
            <string></string>
        </dict>
        </plist>
        EOF
        
    - name: Export IPA file
      run: |
        cd build/ios/project
        xcodebuild -exportArchive -archivePath timeharbor.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist
        
    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-build
        path: |
          build/ios/project/timeharbor.ipa
          build/ios/project/timeharbor.xcarchive
          build/ios/
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          build/
        retention-days: 7
