name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Meteor
      run: |
        curl https://install.meteor.com/ | sh
        
    - name: Install dependencies
      run: |
        meteor npm install
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install iOS Simulator
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcrun simctl list devicetypes
        
    - name: Add iOS platform
      run: |
        meteor add-platform ios
        
    - name: Build iOS app
      run: |
        meteor build ../build --server=https://timeharbor-app.meteorapp.com
        
    - name: Archive iOS app
      run: |
        cd ../build/ios/project
        xcodebuild archive \
          -workspace TimeHarbor.xcworkspace \
          -scheme TimeHarbor \
          -configuration Release \
          -archivePath ../TimeHarbor.xcarchive \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Export IPA
      run: |
        cd ../build/ios
        xcodebuild -exportArchive \
          -archivePath TimeHarbor.xcarchive \
          -exportPath . \
          -exportOptionsPlist exportOptions.plist
          
    - name: Create export options
      run: |
        cd ../build/ios
        cat > exportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>development</string>
          <key>teamID</key>
          <string>\${APPLE_TEAM_ID}</string>
          <key>compileBitcode</key>
          <false/>
          <key>uploadBitcode</key>
          <false/>
        </dict>
        </plist>
        EOF
        
    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          ../build/ios/*.ipa
          ../build/ios/project/
        retention-days: 30
        
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-logs
        path: |
          ../build/ios/project/*.log
          ~/.meteor/logs/
        retention-days: 7